server:
  port: ${SERVICE_PORT:8080}

reactive-clients:
  auth-service-reactive-client:
    baseUrl: ${AUTH_SERVICE_URL:http://localhost:8081}

services:
  routes:
    configs:
      auth-service:
        url: ${AUTH_SERVICE_URL:http://localhost:8081}
      market-service:
        url: ${MARKET_SERVICE_URL:http://localhost:8082}
      delivery-service:
        url: ${DELIVERY_SERVICE_URL:http://localhost:8083}
      notification-service:
        url: ${NOTIFICATION_SERVICE_URL:http://localhost:8084}

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
spring:
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true


